//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_BillDetail = new HashSet<tbl_BillDetail>();
        }
    
        public string product_id { get; set; }
        public string product_name { get; set; }
        public string product_desc { get; set; }
        public Nullable<double> product_import_price { get; set; }
        public Nullable<double> product_export_price { get; set; }
        public Nullable<bool> product_status { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public string cate_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BillDetail> tbl_BillDetail { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
