//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BillDetail
    {
        public int id { get; set; }
        public string bill_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> into_money { get; set; }
    
        public virtual tbl_Bill tbl_Bill { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
