//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Bill()
        {
            this.tbl_BillDetail = new HashSet<tbl_BillDetail>();
        }
    
        public string bill_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<double> total_money { get; set; }
        public Nullable<bool> status_bill { get; set; }
        public string employes_id { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> customer_phone { get; set; }
    
        public virtual tbl_Employees tbl_Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BillDetail> tbl_BillDetail { get; set; }
    }
}
