//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuaha
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employees()
        {
            this.tbl_Bill = new HashSet<tbl_Bill>();
        }
    
        public string employes_id { get; set; }
        public string employes_name { get; set; }
        public string employes_phone { get; set; }
        public string email { get; set; }
        public string employes_address { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> brithday { get; set; }
        public string classifed_id { get; set; }
        public Nullable<bool> status_Employes { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bill> tbl_Bill { get; set; }
        public virtual tbl_Classifed tbl_Classifed { get; set; }
    }
}
